### ISSUE TITLE
老板，搞个按需引入吧，微服务场景下所有服务都引入依赖不够优雅，自己实现一套又麻烦

### ISSUE THREAD

**Issue by zclcs** [houkunlin-starter/system-dict-starter#1]

**Comment by houkunlin** [comment]
能否详细讲一下，例如哪些依赖在哪些场景你觉得是不需要引入的

**Comment by houkunlin** [comment]
新版 1.4.4 已经发布
https://github.com/houkunlin-starter/system-dict-starter/releases/tag/v1.4.4

本次关闭了默认 AMQP 功能，新引入了 Redis 发布/订阅 来做通知其他协同系统刷新字典。
`RefreshDictEvent` 刷新字典事件默认情况下不通知其他系统，需要在配置文件中配置 `system.dict.mq-type` 来决定使用 AMQP/Redis 其中一种方式去通知其他系统。

项目的 AMQP/Redis 依赖都是在编译级别，不会把AMQP/Redis依赖传递给新项目，如需启用相应的功能需要在自己的项目中引入 `org.springframework.boot:spring-boot-starter-data-redis` 或 `org.springframework.boot:spring-boot-starter-amqp` 依赖并配置好相关的连接信息后方可正常使用

**Comment by zclcs** [comment]
> 能否详细讲一下，例如哪些依赖在哪些场景你觉得是不需要引入的

举个栗子，现在系统两个服务，一个字典服务、一个系统服务，两个同时引入依赖，两个服务都会有端点开放，刷新字典成累赘了，系统服务也可以单独刷新，没必要调字典服务去刷新。
字典服务单独引入依赖，系统服务又用不到注解和util。
能否把注解和util做成一个依赖，读写缓存，刷新字典等等做成另外的，这样感觉好一点

**Comment by houkunlin** [comment]
目前暂时还没有拆分的计划，你可以看看下面这种方案是否可行
版本：v1.4.4

**字典服务**
- 可以去掉 `org.springframework.boot:spring-boot-starter-actuator` 依赖
- 去掉 `org.springframework.boot:spring-boot-starter-amqp` 依赖
- 引入 `org.springframework.boot:spring-boot-starter-data-redis` 依赖，使用Redis存储字典信息
- 使用配置 `system.dict.mq-type=none` 关闭通知其他系统刷新字典事件、关闭接收其他系统刷新字典事件

**系统服务**
- 去掉 `org.springframework.boot:spring-boot-starter-actuator` 依赖
- 去掉 `org.springframework.boot:spring-boot-starter-amqp` 依赖
- 引入 `org.springframework.boot:spring-boot-starter-data-redis` 依赖，使用Redis存储字典信息（从Redis读取字典）
- 使用配置 `system.dict.mq-type=none` 关闭通知其他系统刷新字典事件、关闭接收其他系统刷新字典事件


以上配置，`RefreshDictEvent` 和 `RefreshDictValueEvent` 两个事件只会在本服务内生效，不会传播到其他服务，因为这两个事件是使用了 `SpringBoot` 的内置事件机制


`actuator` 的暴露端点需要在配置文件进行以下配置，如果不配置，端点是不会被暴露出来的
```yml
# yaml
management:
  endpoints:
    web:
      cors:
        allowed-headers: '*'
        allowed-methods: '*'
        allowed-origins: '*'
      exposure:
        include: dict,dictSystem,dictRefresh
```
